YOUTUBE_VIDEOS_API_URL = "https://www.googleapis.com/youtube/v3/search"
YOUTUBE_VIDEOS_API_KEY = "xxxxxxxxxx"
EXTERNAL_REQUESTS_TIMEOUT_IN_SECONDS = 10
API_LOCALHOST_BASE_URL = "https://127.0.0.1:8000"
ELASTICSEARCH_DOCKER_BASE_URL = "http://es:9200"
ELASTICSEARCH_LOCALHOST_BASE_URL = "http://127.0.0.1:9200"
