# Generated by Django 4.1.3 on 2022-11-28 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, choices=[('youtube', 'YOUTUBE')], default='youtube', max_length=128, null=True)),
                ('source_video_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source_channel_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source_channel_name', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
